### PR TITLE
Fix two syntax errors

### PR DESCRIPTION
**Pull request by Moini**
On the forum, there's someone trying out the code - we're doing remote debugging...

### CODE REVIEW

**Comment by U17A** [comment]
I submitted an issue because of this, thanks for the fix. Hope they merge it soon.

**Comment by Moini** [comment]
Guess I can close this now, @jnweiger ? I got an email stating 

> @jnweiger requested changes on this pull request.
>
> Merged some of this into github.com/fablabnbg/inkscape-text2hershey
> 
> Most of the code seems to be missing here. Do not release.

- but I cannot find this here. It's a bit confusing... But it looks as if the two things that were fixed here are now in the master branch.

**Comment by jnweiger** [comment]
We can close here. Upstream has a new version that includes what was attempted here.

**Comment by Moini** [comment]
Yep. Have you seen it yet?

**Pull request closed without merging**
